#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""added job table

Revision ID: 94cc918a6ddf
Revises: 1aca21c75479
Create Date: 2019-10-17 18:39:53.859591

"""

# revision identifiers, used by Alembic.
revision = '94cc918a6ddf'
down_revision = '1aca21c75479'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import airflow.utils.sqlalchemy as aus


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dag_id', sa.String(length=250), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('job_type', sa.String(length=30), nullable=True),
    sa.Column('start_date', aus.UtcDateTime(timezone=True), nullable=True),
    sa.Column('end_date', aus.UtcDateTime(timezone=True), nullable=True),
    sa.Column('latest_heartbeat', aus.UtcDateTime(timezone=True), nullable=True),
    sa.Column('executor_class', sa.String(length=500), nullable=True),
    sa.Column('hostname', sa.String(length=500), nullable=True),
    sa.Column('unixname', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_state_heartbeat', 'job', ['state', 'latest_heartbeat'], unique=False)
    op.create_index('job_type_heart', 'job', ['job_type', 'latest_heartbeat'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('job_type_heart', table_name='job')
    op.drop_index('idx_job_state_heartbeat', table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
